services:
  # Databases
  postgres:
    image: postgres:17
    container_name: triumph-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-robin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-batman}
      POSTGRES_DB: ${POSTGRES_DB:-triumph}
    volumes:
      - postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: triumph-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-robin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-batman}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-triumph}
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Database management tools
  adminer:
    image: adminer
    container_name: triumph-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express
    container_name: triumph-mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-robin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-batman}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-robin}:${MONGO_INITDB_ROOT_PASSWORD:-batman}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb:
  postgres:
