services:
  # Frontend frameworks
  react:
    build:
      context: ./frontend
      dockerfile: ./react/Dockerfile
    container_name: react

  # Backend frameworks
  express:
    build:
      context: ./backend
      dockerfile: ./infrastructure/frameworks/express/Dockerfile
    container_name: express

  nest:
    build:
      context: ./backend
      dockerfile: ./infrastructure/frameworks/nest/Dockerfile
    container_name: nest

  # Databases
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-robin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-batman}
      POSTGRES_DB: ${POSTGRES_DB:-triumph}
    volumes:
      - postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-robin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-batman}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-triumph}
    volumes:
      - mongodb:/data/db

  # Database management tools
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-robin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-batman}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-robin}:${MONGO_INITDB_ROOT_PASSWORD:-batman}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

volumes:
  mongodb:
  postgres:
