services:
  # Frontend frameworks
  react:
    image: node:lts-alpine
    working_dir: /home/node/app
    command: sh -c "npm i && npm run dev"
    container_name: react
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/react:/home/node/app"

  # Backend frameworks
  express:
    image: node:lts-alpine
    working_dir: /home/node/app
    command: sh -c "npm i && npm run dev"
    container_name: express
    ports:
      - "3000:3000"
    volumes:
      - "./backend/infrastructure/frameworks/express:/home/node/app"

  nest:
    image: node:lts-alpine
    working_dir: /home/node/app
    command: sh -c "npm i && npm run start:dev"
    container_name: nest
    ports:
      - "3001:3000"
    volumes:
      - "./backend/infrastructure/frameworks/nest:/home/node/app"

  # Databases
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-robin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-batman}
      POSTGRES_DB: ${POSTGRES_DB:-triumph}
    volumes:
      - postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-robin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-batman}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-triumph}
    volumes:
      - mongodb:/data/db

  # Database management tools
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-robin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-batman}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-robin}:${MONGO_INITDB_ROOT_PASSWORD:-batman}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

volumes:
  mongodb:
  postgres:
